name: Schoolwars
version: '${project.version}'
main: main.bazcraft.schoolwars.Schoolwars
api-version: 1.17
authors: [ RuneHeus, NoahUyttebroeck ]
depend: [Citizens]
commands:
  despawnnpc:
    aliases:
      - removenpc
      - deletenpc
    usage: /<command>
  spawnnpc:
    usage: /<command>
    aliases:
      - npc
      - getnpc
  spelers:
    usage: print een lijst van alle spelers die zich momenteel in de server bevinden
  pad:
    usage: geen idee
  fstart:
    usage: Start het spel direct
  endgame:
    usage: stopt het spel direct
  antwoord:
    usage: /<command> <antwoord>
